config-version: 2
name: 'sap'
version: '0.7.0'
require-dbt-version: [">=1.3.0", "<3.0.0"]
models:
  sap:
    +materialized: table
    +schema: kel_mdls_sap
    staging:
      +materialized: view
    extractor_reports:
      intermediate:
        +materialized: table
    sales_and_procurement:
      star_schema:
        intermediate:
          +materialized: view
    compatibility_views:
      +schema: kel_mdls_sap_comp_views
      +materialized: view
      intermediate:
        +materialized: ephemeral
        int_cosp__acdoca_derived:
          +materialized: view

